apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "petclinic-simple-chart.configname" . }}
data:
  # Config data
  petclinic_topic_name: petclinic-topic
  petclinic_version: v1

  #{{- toYaml . | nindent 2 }}