apiVersion: v1
kind: Service
metadata:
  name: {{ include "petclinic-simple-chart.fullname" . | nindent 1 }}
  labels:
    {{- include "petclinic-simple-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "petclinic-simple-chart.selectorLabels" . | nindent 4 }}
