apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: petclinic-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 8080
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: petclinic
spec:
  hosts:
    - "*"
  gateways:
    - petclinic-gateway
  http:
  - name: "route-config-1"
    match:
    - uri:
      prefix: "/app1"
    route:
    - destination:
        host: app1.default.svc.cluster.local
        port:
          number: 8080
  - name: "route-config-2"
    match:
    - uri:
      prefix: "/app2"
    route:
    - destination:
        host: app2.default.svc.cluster.local
        port:
          number: 80