apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: petclinic-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 8080
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: petclinic
spec:
  hosts:
    - "*"
  gateways:
    - petclinic-gateway
  http:
  - match:
      - uri:
        prefix: app1
    route:
    - destination:
        host: petclinic
        port:
          number: 8080
  - match:
      - uri:
        prefix: app2
    route:
    - destination:
        host: petclinic-clone
        port:
          number: 80