apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: petclinic-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 8080
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: petclinic
spec:
  hosts:
    - "*"
  gateways:
    - petclinic-gateway
  http:
    - match:
        - port: 8080
      route:
      - destination:
          host: petclinic
          port:
            number: 8080
