apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: petclinic-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: petclinic-routing
spec:
  hosts:
    - "deployment-app1-petclinic-simple-char.default.svc.cluster.local"
    - "deployment-app2-petclinic-simple-char.default.svc.cluster.local"
  gateways:
    - petclinic-gateway
  http:
  - name: "route-config-1"
    match:
    - uri:
        prefix: /app1
    rewrite:
      uri: /
    route:
    - destination:
        host: deployment-app1-petclinic-simple-char.default.svc.cluster.local
        port:
          number: 8080
  - name: "route-config-2"
    match:
    - uri:
        prefix: /app2
    rewrite:
      uri: /
    route:
    - destination:
        host: deployment-app2-petclinic-simple-char.default.svc.cluster.local
        port:
          number: 80